### ISSUE TITLE
What are the license terms?

### ISSUE THREAD

**Issue by Revisor** [vivait/backoff#2]
Hi, I wanted to commend you on the code. I went through various exponential backoff implementations on Packagist and I like yours the best - using an interface, clear method signatures (no options in arrays etc.), tagged release, comprehensive tests. Good work.

I just wanted to ask about the license terms. Composer.json says the license is "proprietary" and there is no other information about the license as far as I can find.

Could you please clarify the license terms?

Thanks.

**Comment by kieljohn** [comment]
Thanks for your comment, apologises for it has taken so long for this to be noticed. It is MIT licensed.

**Comment by Revisor** [comment]
Thank you for getting back to me.
